### ISSUE TITLE
[Proposal] TypeScript Base (e concetti di programmazione TypeSafe)

### ISSUE THREAD

**Issue by kandros** [casavo/tech-learning#1]
# A taste of TypeScript (done in 5 minutes 🤪)

<img width="1792" alt="Screenshot 2020-06-09 at 12 12 17" src="https://user-images.githubusercontent.com/4562878/84136251-52676b80-aa4b-11ea-8df6-a1e3b4532084.png">

<img width="745" alt="Screenshot 2020-06-09 at 12 05 09" src="https://user-images.githubusercontent.com/4562878/84136365-7aef6580-aa4b-11ea-9c67-fd436564ce47.png">

<img width="771" alt="Screenshot 2020-06-09 at 12 10 47" src="https://user-images.githubusercontent.com/4562878/84136342-72972a80-aa4b-11ea-9630-5baf74aa86f7.png">

<img width="802" alt="Screenshot 2020-06-09 at 12 12 54" src="https://user-images.githubusercontent.com/4562878/84136318-69a65900-aa4b-11ea-890b-e36782cc7e96.png">

<img width="369" alt="Screenshot 2020-06-09 at 12 15 51" src="https://user-images.githubusercontent.com/4562878/84136338-7165fd80-aa4b-11ea-9110-e8328512c985.png">

<img width="735" alt="Screenshot 2020-06-09 at 12 16 02" src="https://user-images.githubusercontent.com/4562878/84136241-4ed3e480-aa4b-11ea-8402-acb97600a56d.png">

<img width="782" alt="Screenshot 2020-06-09 at 12 13 31" src="https://user-images.githubusercontent.com/4562878/84136223-4aa7c700-aa4b-11ea-94ee-fcf44e417c54.png">

## A chi e' rivolto?

chiunque vuole imparare di piu su un linguaggio fortemente tipizzato, gran parte delle conoscenze (eg uso dei generics, tipizzazione di lambda functions ecc) sono applicabili a contesti diversi per esempio Kotlin

### Stima di durata

3 ore

## Why
TypeScript e' diventato in poco tempo uno dei miei linguaggi preferiti, ha un TypeSystem davvero potente che permette di esprimere concetti in modo chiaro e TypeSafe, con feature di cui quando uso altri linguaggi sento la mancanza (golang 🙄)

E' utilizzabile sia per Frontend che Backend che per scripting (Node ha una standard library con delle API che renderono scripting molto comodo)

## What 

Imparare le basi di TypeScript e del suo TypeSystem, in modo da farsi venire l' acquolina in bocca e approfondire in autonomia

## How

Un mini corso frontale per fare da showcase dell feature piu interessanti e  spiegarne il funzionamento, focus su setup minimale di un progetto TS e scrittura di script TypeSafe

**Comment by xpepper** [comment]
is it this relevant (and if so I would think about merging it) or too old now?

**Comment by kandros** [comment]
too old, better closing

**Comment by xpepper** [comment]
Yes, that's a pity because of the content and of your effort.
I would really like to keep our tech-learning up to date and useful for us...
